---
- name: 'Install etcd on etcd nodes'
  hosts: 'etcd_nodes'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'install_and_configure_etcd'
      vars:
        enable_api_v2: 'true'
        etcd_advertise_client_urls: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2379"
        etcd_listen_client_urls: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2379,http://localhost:2379"
        etcd_listen_peer_urls: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2380,http://127.0.0.1:7001"
        etcd_initial_advertise_peer_urls: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2380"
        etcd_servers_group: 'etcd_nodes'
        etcd_initial_cluster_state: 'new'
        etcd_initial_cluster_token: 'patroni'
