---
- name: 'Gather facts on all VMs'
  hosts: 'all'
  gather_facts: 'yes'

- name: 'Install and configure patroni on patroni nodes'
  hosts: 'patroni_nodes'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'patroni_postgresql_cluster'
      vars:
        postgres_version: '12'
        patroni_servers_group: 'patroni_nodes'
        etcd_servers_group: 'etcd_nodes'
        patroni_bootstrap_users:
          - name: 'admin'
            password: 'admin'
            options:
              - createrole
              - createdb
        patroni_postgresql_authentication:
          - name: 'replication'
            username: 'replicator'
            password: 'password'
          - name: 'superuser'
            username: 'postgres'
            password: 'password'
        patroni_tags:
          nofailover: 'false'
          noloadbalance: 'false'
          clonefrom: 'false'
          nosync: 'false'
