---
- name: 'Gather facts on all VMs'
  hosts: 'all'
  gather_facts: 'yes'

- name: 'Install haproxy'
  hosts: 'haproxy_server'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'haproxy'

  tasks:

    - name: 'Create /etc/haproxy/haproxy.cfg'
      template:
        src: 'etc_haproxy_haproxy.cfg.j2'
        dest: '/etc/haproxy/haproxy.cfg'
        owner: 'root'
        group: 'root'
        mode: '0600'
      notify:
        - 'restart haproxy'

    - name: 'Start and enable haproxy'
      service:
        name: 'haproxy.service'
        state: 'started'
        enabled: 'true'
