---
- name: 'Basic configuration on all nodes'
  hosts: 'all'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'zypper_ref_accept_keys'
    - role: 'minimal_bashrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'create_a_vimrc'
      vars:
        additional_users: "{{ ansible_user }}"

- name: 'Run playbook playbook-vagrant-etcd.yml'
  import_playbook: playbook-vagrant-etcd.yml

- name: 'Install haproxy on etcd nodes'
  hosts: 'haproxy_server'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'haproxy'

  tasks:

    - name: 'Create /etc/haproxy/haproxy.cfg'
      template:
        src: 'etc_haproxy_haproxy.cfg.j2'
        dest: '/etc/haproxy/haproxy.cfg'
        owner: 'root'
        group: 'root'
        mode: '0600'
    #  notify:
    #    - 'restart haproxy'

    - name: 'Start and enable haproxy'
      service:
        name: 'haproxy.service'
        state: 'started'
        enabled: 'true'

- name: 'Install patroni on patroni nodes'
  hosts: 'patroni_nodes'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'add_zypper_repository'
      vars:
        repository_name: 'home_ojkastl_buildservice_patroni'
        repository_baseurl: 'https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/Patroni/15.3'
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'patroni'
          - 'postgresql12'
          - 'postgresql12-server'

  tasks:

    - name: 'Create directory /mnt/patroni/'
      file:
        path: '/mnt/patroni/'
        state: 'directory'
        owner: 'postgres'
        group: 'postgres'
        mode: '0700'

    - name: 'Create /etc/patroni.yml'
      template:
        src: 'patroni.yml.j2'
        dest: '/etc/patroni.yml'
        owner: 'root'
        group: 'root'
        mode: '0600'

    - name: 'Create /etc/systemd/system/patroni.service'
      template:
        src: 'patroni.service.j2'
        dest: '/etc/systemd/system/patroni.service'
        owner: 'root'
        group: 'root'
        mode: '0644'
