---
- name: 'Basic configuration on all nodes'
  hosts: 'all'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'zypper_ref_accept_keys'
    - role: 'minimal_bashrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'create_a_vimrc'
      vars:
        additional_users: "{{ ansible_user }}"

- name: 'Run playbook playbook-vagrant-etcd.yml'
  import_playbook: playbook-vagrant-etcd.yml

- name: 'Run playbook playbook-vagrant-haproxy.yml'
  import_playbook: playbook-vagrant-haproxy.yml

- name: 'Run playbook playbook-vagrant-patroni.yml'
  import_playbook: playbook-vagrant-patroni.yml
