---
- name: 'Gather facts on all VMs'
  hosts: 'all'
  gather_facts: 'yes'

- name: 'Install haproxy'
  hosts: 'haproxy_server'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'install_and_configure_haproxy'
      vars:
        destinations:
          - type: 'simple'
            name: 'postgres'
            port: '5000'
            option: 'httpchk'
            option_configuration: 'expect status 200'
            default_server: 'inter 3s fall 3 rise 2 on-marked-down shutdown-sessions'
            backend_options: 'maxconn 100 check port 8008'
            backend_prefix: 'postgresql_'
            backend_port: '5432'
            backends_group: 'patroni_nodes'
